apiVersion: v2
name: velero
description: A Helm chart for Velero - Kubernetes Backup and Restore
type: application
version: 0.1.0
appVersion: "v1.18.0"
keywords:
  - kubernetes
  - backup
  - restore
  - velero
home: https://velero.io
maintainers:
  - name: velero
sources:
  - https://github.com/vmware-tanzu/velero
