apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: velero
  labels:
    app.kubernetes.io/app-component: velero
    app: velero
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
