{{- if .Values.backupStorageLocation.enabled }}
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: {{ .Values.backupStorageLocation.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/app-component: velero
    app: velero
spec:
  provider: {{ .Values.backupStorageLocation.provider }}
  default: {{ .Values.backupStorageLocation.default }}
  accessMode: {{ .Values.backupStorageLocation.accessMode }}
  objectStorage:
    bucket: {{ .Values.backupStorageLocation.bucket }}
    {{- if .Values.backupStorageLocation.prefix }}
    prefix: {{ .Values.backupStorageLocation.prefix }}
    {{- end }}
  config:
    {{- range $key, $value := .Values.backupStorageLocation.config }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- if .Values.credentials.useSecret }}
  credential:
    name: {{ .Values.credentials.name }}
    key: cloud
  {{- end }}
{{- end }}
