{{- if .Values.volumeSnapshotLocation.enabled }}
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: {{ .Values.volumeSnapshotLocation.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/app-component: velero
    app: velero
spec:
  provider: {{ .Values.volumeSnapshotLocation.provider }}
  config:
    {{- range $key, $value := .Values.volumeSnapshotLocation.config }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- if .Values.credentials.useSecret }}
  credential:
    name: {{ .Values.credentials.name }}
    key: cloud
  {{- end }}
{{- end }}
