{{- if .Values.credentials.useSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/app-component: velero
    app: velero
type: Opaque
stringData:
  cloud: |
{{ .Values.credentials.secretContents.cloud | indent 4 }}
{{- end }}
