apiVersion: v2
name: csi-disk
description: A Helm chart for CDS CSI Disk Driver - Kubernetes CSI Driver for Disk Storage
type: application
version: 0.1.0
appVersion: "v1.0.1-eks"
keywords:
  - kubernetes
  - csi
  - storage
  - disk
  - cds
  - capital-online
home: https://github.com/capitalonline/csi-disk
maintainers:
  - name: capital-online
sources:
  - https://github.com/capitalonline/csi-disk
