apiVersion: v1
kind: Service
metadata:
  labels:
    name: eks-disk-csi-cds-controller
  name: eks-disk-csi-cds-controller
  namespace: kube-system
spec:
  ports:
    - name: healthz
      port: 9810
  selector:
    app: eks-disk-csi-cds-controller
