apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
{{- if .Values.prometheus.auth.enabled }}
    nginx.ingress.kubernetes.io/auth-secret: basic-auth-secret
    nginx.ingress.kubernetes.io/auth-type: basic
{{- end }}
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
  name: prometheus
  namespace: monitoring
spec:
  ingressClassName: nginx
  rules:
{{- range .Values.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      - backend:
          service:
            name: prometheus-k8s
            port:
              number: 9090
        path: /
        pathType: ImplementationSpecific
{{- end }}
  tls:
    - hosts:
{{- range .Values.ingress.hosts }}
        - {{ . }}
{{- end }}
      secretName: monitoring-certs
