{{- if .Values.prometheus.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-secret
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: auth
type: Opaque
data:
  auth: {{ .Values.prometheus.auth.htpasswd | b64enc }}
{{- end }}

