---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: backups.velero.io
  labels:
    app.kubernetes.io/name: velero
    component: velero
spec:
  group: velero.io
  names:
    kind: Backup
    listKind: BackupList
    plural: backups
    singular: backup
    categories:
      - velero
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: STATUS
          type: string
          description: Backup 状态
          jsonPath: .status.phase
        - name: ERRORS
          type: integer
          description: 错误数
          jsonPath: .status.errors
        - name: WARNINGS
          type: integer
          description: 警告数
          jsonPath: .status.warnings
        - name: CREATED
          type: date
          description: 备份开始时间
          jsonPath: .status.startTimestamp
        - name: EXPIRES
          type: date
          description: 过期时间
          jsonPath: .status.expiration
        - name: STORAGE LOCATION
          type: string
          description: 备份存储位置
          jsonPath: .spec.storageLocation
        - name: AGE
          type: date
          jsonPath: .metadata.creationTimestamp
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: backuprepositories.velero.io
  labels:
    app.kubernetes.io/name: velero
    component: velero
spec:
  group: velero.io
  names:
    kind: BackupRepository
    listKind: BackupRepositoryList
    plural: backuprepositories
    singular: backuprepository
    categories:
      - velero
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: AGE
          type: date
          jsonPath: .metadata.creationTimestamp
        - name: READY
          type: string
          jsonPath: .status.phase
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: backupstoragelocations.velero.io
  labels:
    app.kubernetes.io/name: velero
    component: velero
spec:
  group: velero.io
  names:
    kind: BackupStorageLocation
    listKind: BackupStorageLocationList
    plural: backupstoragelocations
    singular: backupstoragelocation
    shortNames:
      - bsl
    categories:
      - velero
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: PHASE
          type: string
          description: 连接状态
          jsonPath: .status.phase
        - name: LAST VALIDATED
          type: date
          description: 最近验证时间
          jsonPath: .status.lastValidationTime
        - name: AGE
          type: date
          jsonPath: .metadata.creationTimestamp
        - name: DEFAULT
          type: boolean
          jsonPath: .spec.default
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: deletebackuprequests.velero.io
  labels:
    app.kubernetes.io/name: velero
    component: velero
spec:
  group: velero.io
  names:
    kind: DeleteBackupRequest
    listKind: DeleteBackupRequestList
    plural: deletebackuprequests
    singular: deletebackuprequest
    categories:
      - velero
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: AGE
          type: date
          jsonPath: .metadata.creationTimestamp
        - name: BACKUP
          type: string
          jsonPath: .spec.backupName
        - name: STATUS
          type: string
          jsonPath: .status.phase
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: downloadrequests.velero.io
  labels:
    app.kubernetes.io/name: velero
    component: velero
spec:
  group: velero.io
  names:
    kind: DownloadRequest
    listKind: DownloadRequestList
    plural: downloadrequests
    singular: downloadrequest
    categories:
      - velero
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: AGE
          type: date
          jsonPath: .metadata.creationTimestamp
        - name: STATUS
          type: string
          jsonPath: .status.phase
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podvolumebackups.velero.io
  labels:
    app.kubernetes.io/name: velero
    component: velero
spec:
  group: velero.io
  names:
    kind: PodVolumeBackup
    listKind: PodVolumeBackupList
    plural: podvolumebackups
    singular: podvolumebackup
    categories:
      - velero
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: AGE
          type: date
          jsonPath: .metadata.creationTimestamp
        - name: STATUS
          type: string
          jsonPath: .status.phase
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podvolumerestores.velero.io
  labels:
    app.kubernetes.io/name: velero
    component: velero
spec:
  group: velero.io
  names:
    kind: PodVolumeRestore
    listKind: PodVolumeRestoreList
    plural: podvolumerestores
    singular: podvolumerestore
    categories:
      - velero
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: AGE
          type: date
          jsonPath: .metadata.creationTimestamp
        - name: STATUS
          type: string
          jsonPath: .status.phase
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: restores.velero.io
  labels:
    app.kubernetes.io/name: velero
    component: velero
spec:
  group: velero.io
  names:
    kind: Restore
    listKind: RestoreList
    plural: restores
    singular: restore
    categories:
      - velero
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: BACKUP
          type: string
          description: 关联的备份名称
          jsonPath: .spec.backupName
        - name: STATUS
          type: string
          description: 恢复状态
          jsonPath: .status.phase
        - name: STARTED
          type: date
          description: 开始时间
          jsonPath: .status.startTimestamp
        - name: COMPLETED
          type: date
          description: 完成时间
          jsonPath: .status.completionTimestamp
        - name: ERRORS
          type: integer
          description: 错误数
          jsonPath: .status.errors
        - name: WARNINGS
          type: integer
          description: 警告数
          jsonPath: .status.warnings
        - name: AGE
          type: date
          jsonPath: .metadata.creationTimestamp
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: schedules.velero.io
  labels:
    app.kubernetes.io/name: velero
    component: velero
spec:
  group: velero.io
  names:
    kind: Schedule
    listKind: ScheduleList
    plural: schedules
    singular: schedule
    categories:
      - velero
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: STATUS
          type: string
          description: 调度状态
          jsonPath: .status.phase
        - name: SCHEDULE
          type: string
          description: Cron 表达式
          jsonPath: .spec.schedule
        - name: BACKUP TTL
          type: string
          description: 备份保留时间
          jsonPath: .spec.template.ttl
        - name: LAST BACKUP
          type: date
          description: 最近一次备份时间
          jsonPath: .status.lastBackup
        - name: AGE
          type: date
          jsonPath: .metadata.creationTimestamp
        - name: PAUSED
          type: boolean
          jsonPath: .spec.paused
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: serverstatusrequests.velero.io
  labels:
    app.kubernetes.io/name: velero
    component: velero
spec:
  group: velero.io
  names:
    kind: ServerStatusRequest
    listKind: ServerStatusRequestList
    plural: serverstatusrequests
    singular: serverstatusrequest
    shortNames:
      - ssr
    categories:
      - velero
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: volumesnapshotlocations.velero.io
  labels:
    app.kubernetes.io/name: velero
    component: velero
spec:
  group: velero.io
  names:
    kind: VolumeSnapshotLocation
    listKind: VolumeSnapshotLocationList
    plural: volumesnapshotlocations
    singular: volumesnapshotlocation
    shortNames:
      - vsl
    categories:
      - velero
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: PHASE
          type: string
          jsonPath: .status.phase
        - name: AGE
          type: date
          jsonPath: .metadata.creationTimestamp
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: datadownloads.velero.io
  labels:
    app.kubernetes.io/name: velero
    component: velero
spec:
  group: velero.io
  names:
    kind: DataDownload
    listKind: DataDownloadList
    plural: datadownloads
    singular: datadownload
    categories:
      - velero
  scope: Namespaced
  versions:
    - name: v2alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: STATUS
          type: string
          jsonPath: .status.phase
        - name: AGE
          type: date
          jsonPath: .metadata.creationTimestamp
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: datauploads.velero.io
  labels:
    app.kubernetes.io/name: velero
    component: velero
spec:
  group: velero.io
  names:
    kind: DataUpload
    listKind: DataUploadList
    plural: datauploads
    singular: dataupload
    categories:
      - velero
  scope: Namespaced
  versions:
    - name: v2alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: STATUS
          type: string
          jsonPath: .status.phase
        - name: AGE
          type: date
          jsonPath: .metadata.creationTimestamp
