---
apiVersion: v1
kind: Service
metadata:
  name: p2p-accelerator
  namespace: kube-system
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metrics
    nodePort: 30022
    port: 9090
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/component: p2p-accelerator
    app.kubernetes.io/instance: p2p-accelerator
    app.kubernetes.io/name: p2p-accelerator
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: p2p-accelerator-bootstrap
  namespace: kube-system
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: router
    port: 5001
    protocol: TCP
    targetPort: 5001
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/component: p2p-accelerator
    app.kubernetes.io/instance: p2p-accelerator
    app.kubernetes.io/name: p2p-accelerator
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: p2p-accelerator-registry
  namespace: kube-system
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: registry
    nodePort: 30021
    port: 5000
    protocol: TCP
    targetPort: registry
  selector:
    app.kubernetes.io/component: p2p-accelerator
    app.kubernetes.io/instance: p2p-accelerator
    app.kubernetes.io/name: p2p-accelerator
  sessionAffinity: None
  type: NodePort
