{{- if .Values.alertmanager.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-auth-secret
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/component: auth
type: Opaque
data:
  auth: {{ .Values.alertmanager.auth.htpasswd | b64enc }}
{{- end }}

