apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-secret: alertmanager-auth-secret
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
  name: alarm
  namespace: monitoring
spec:
  ingressClassName: nginx
  rules:
{{- range .Values.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      - backend:
          service:
            name: alertmanager-operated
            port:
              number: 9093
        path: /
        pathType: ImplementationSpecific
{{- end }}
  tls:
    - hosts:
{{- range .Values.ingress.hosts }}
        - {{ . }}
{{- end }}
      secretName: monitoring-certs
